#define Activity_Dialog	1
#define Assignment	4
#define Attach	5
#define Attributes	6
#define Automatic_Shape_Connection	7
#define Break_Loop	8
#define Clock	9
#define Comment	10
#define Conditional	11
#define Connecting_Shapes	12
#define Connections	13
#define Continuous	14
#define Converting_Between_Numeric_Types	15
#define Converting_Existing_Flow_Charts_to_Process_Simulator_Models	16
#define Dec	18
#define Defining_a_Process	19
#define Defining_Connection_Properties	20
#define Defining_Logic	21
#define Defining_Shape_Properties	22
#define Defining_Variables_and_Attributes	23
#define Detach	24
#define Display	25
#define Distribution_Builder	26
#define Distributions	27
#define DownQty	28
#define Else	29
#define Else_If	30
#define Entity	31
#define Entity_Dialog	32
#define Entries	33
#define Exponential	36
#define Flow_Control	37
#define Free	38
#define FreeCap	39
#define FreeUnits	40
#define Functions	41
#define Get	42
#define Getting_Started_with_Process_Simulator	44
#define GroupQty	45
#define If	46
#define Inc	47
#define IncCost	48
#define IncInventory	49
#define Local_Variable	51
#define Log	52
#define Logic_Builder	53
#define Modeling_Elements	54
#define Modeling_Environment	55
#define Natural_Logarithm	56
#define Order	58
#define Ordered_Arrival	60
#define Ordered_Routing	61
#define OwnedResource	62
#define Pause	63
#define Percentage	64
#define Periodic	65
#define Placing_and_Connecting_Shapes	66
#define Placing_Shapes	67
#define Process_Simulator_Help	68
#define Prompt	71
#define Random	72
#define Reset_Stats	73
#define Resource_Dialog	74
#define ResQty	75
#define Return	76
#define Right_Click_Menu	77
#define Round	78
#define Routing_Dialog	79
#define Run_Time_Options	81
#define Scenarios	83
#define Scheduled	84
#define Shapes	85
#define Simulation	87
#define Simulation_and_Options	88
#define Simulation_Object_Explorer	89
#define Simulation_Properties	90
#define Square_Root	91
#define Statements	92
#define Stop	93
#define Technical_Support	94
#define Terminating_a_Process	95
#define TimesUsed	96
#define Untitled_Document	99
#define Use	100
#define Using_Process_Simulator	101
#define Variables	103
#define Viewing_Output_Results	104
#define Wait	105
#define Wait_Until	106
#define Welcome_to_Process_Simulator	107
#define While_Do	108
